run:
  issues-exit-code: 1
  paths:
    - ./internal/...
    - ./cmd/...
    - ./pkg/...

issues:
  exclude-rules:
    - path: .*/opt/homebrew/.*
      linters:
        - all
    - path: .*/go/pkg/mod/.*
      linters:
        - all
    - path: vendor/.*
      linters:
        - all
    - path: _gen\.go
      linters:
        - all
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl


linters:
  disable-all: true
  enable:
    - asasalint
    - cyclop
    - depguard
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gomnd
    - gosimple
    - gosec
    - govet
    - misspell
    - musttag
    - prealloc
    - predeclared
    - usestdlibvars
    - whitespace
    - wsl
    - revive
    - bodyclose
    - exportloopref
    - ineffassign
    - nolintlint
    - stylecheck
    - unconvert

linters-settings:
  asasalint:
    exclude:
      - \.Debugf
      - \.Infof
      - \.Warnf
      - \.Errorf
      - \.Fatalf
    ignore-test: true
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
    ignore-tests: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 500
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - '0666'
      - '0755'
    ignored-functions:
      - '^math\.'
      - '^context\.'
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
      - nilfunc
      - nilness
  revive:
    severity: error
    enable-all-rules: true
    confidence: 0.8
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
      - name: unused-receiver
        severity: warning
        disabled: false
      - name: line-length-limit
        severity: warning
        disabled: true
        arguments: [80]
      - name: unchecked-type-assertion
        severity: warning
        disabled: true
      - name: add-constant
        severity: warning
        disabled: false
        arguments:
          - maxLitCount: "10"
            allowStrs: '""'
            allowInts: "0,1,2,3,4"
      - name: cognitive-complexity
        severity: warning
        disabled: true
        arguments: [10]
      - name: max-public-structs
        severity: warning
        disabled: false
        arguments: [10]
  nolintlint:
    require-explanation: true
    require-specific: true
  depguard:
    rules:
      main:
        files:
          - "!**/*_a _file.go"
        allow:
          - $gostd
          - github.com/rezakhdemix
          - github.com/redis
        deny:
          - pkg: "github.com/pkg/example"
            desc: should be replaced by blah blah package