apiVersion: v1
kind: ConfigMap
metadata:
  name: finly-backend-config
  namespace: default
data:
  ENV: "dev"
  HTTP_PORT: "8080"
  DB_HOST: "postgres-service.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "finly"
  DB_SSLMODE: "disable"
  REDIS_HOST: "redis-service.default.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"