definitions:
  finly-backend_internal_service_auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  finly-backend_internal_service_auth.LoginResponse:
    properties:
      token:
        type: string
    type: object
  finly-backend_internal_service_auth.LogoutRequest:
    properties:
      authToken:
        type: string
    type: object
  finly-backend_internal_service_auth.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  finly-backend_internal_service_auth.MeResponse:
    properties:
      email:
        type: string
      first_name:
        maxLength: 100
        minLength: 1
        type: string
      last_name:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - email
    - first_name
    - last_name
    type: object
  finly-backend_internal_service_auth.RefreshTokenRequest:
    properties:
      authToken:
        type: string
    type: object
  finly-backend_internal_service_auth.RefreshTokenResponse:
    properties:
      token:
        type: string
    type: object
  finly-backend_internal_service_auth.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        maxLength: 100
        minLength: 1
        type: string
      last_name:
        maxLength: 100
        minLength: 1
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  finly-backend_internal_service_auth.RegisterResponse:
    properties:
      token:
        type: string
    type: object
  finly-backend_internal_service_budget.CreateBudgetRequest:
    properties:
      currency:
        type: string
      name:
        type: string
      userID:
        type: string
    required:
    - currency
    - name
    - userID
    type: object
  finly-backend_internal_service_budget.CreateBudgetResponse:
    type: object
  finly-backend_internal_service_budget.GetBudgetByIDResponse:
    properties:
      amount:
        type: integer
      currency:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      description: Authenticates a user with the provided credentials
      operationId: login-user
      parameters:
      - description: User Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.LoginResponse'
      summary: Login a user
      tags:
      - User
  /auth/logout:
    post:
      description: Logs out a user by invalidating their authentication token
      operationId: logout-user
      parameters:
      - description: Authentication Token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.LogoutResponse'
      summary: Logout a user
      tags:
      - User
  /auth/me:
    post:
      description: Retrieves information about the currently authenticated user
      operationId: get-user-info
      parameters:
      - description: Authentication Token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.MeResponse'
      summary: Get user information
      tags:
      - User
  /auth/refresh:
    post:
      description: Refreshes a user's authentication token by generating a new one
      operationId: refresh-token
      parameters:
      - description: Authentication Token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.RefreshTokenResponse'
      summary: Refresh a user token
      tags:
      - User
  /auth/register:
    post:
      description: Registers a new user with the provided details
      operationId: register-user
      parameters:
      - description: User Details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.RegisterResponse'
      summary: RegisterUser a new user
      tags:
      - User
  /budget:
    post:
      description: Creates a new budget for the user with the provided details
      operationId: create-budget
      parameters:
      - description: Budget Details
        in: body
        name: budget
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_budget.CreateBudgetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_budget.CreateBudgetResponse'
      summary: Create a new budget
      tags:
      - Budget
  /budget/{budget_id}:
    get:
      description: Retrieves a budget by its ID for the specified user
      operationId: get-budget-by-id
      parameters:
      - description: Budget ID
        in: path
        name: budget_id
        required: true
        type: string
      - description: User ID
        in: header
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_budget.GetBudgetByIDResponse'
      summary: Get budget by ID
      tags:
      - Budget
swagger: "2.0"
