definitions:
  finly-backend_internal_domain_enums_e_transaction_type.Enum:
    enum:
    - deposit
    - withdraw
    type: string
    x-enum-varnames:
    - Deposit
    - Withdraw
  finly-backend_internal_service_auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 100
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
  finly-backend_internal_service_auth.LoginResponse:
    properties:
      token:
        type: string
    type: object
  finly-backend_internal_service_auth.LogoutRequest:
    properties:
      authToken:
        type: string
    type: object
  finly-backend_internal_service_auth.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  finly-backend_internal_service_auth.MeResponse:
    properties:
      email:
        type: string
      first_name:
        maxLength: 100
        minLength: 1
        type: string
      last_name:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - email
    - first_name
    - last_name
    type: object
  finly-backend_internal_service_auth.RefreshTokenRequest:
    properties:
      authToken:
        type: string
    type: object
  finly-backend_internal_service_auth.RefreshTokenResponse:
    properties:
      token:
        type: string
    type: object
  finly-backend_internal_service_auth.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        maxLength: 100
        minLength: 1
        type: string
      last_name:
        maxLength: 100
        minLength: 1
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  finly-backend_internal_service_auth.RegisterResponse:
    properties:
      token:
        type: string
    type: object
  finly-backend_internal_service_budget.CreateBudgetRequest:
    properties:
      currency:
        type: string
      userID:
        type: string
    required:
    - currency
    - userID
    type: object
  finly-backend_internal_service_budget.CreateBudgetResponse:
    properties:
      id:
        type: string
    type: object
  finly-backend_internal_service_budget.GetBudgetByIDResponse:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      currency:
        type: string
      id:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  finly-backend_internal_service_category.CreateCategoryRequest:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_user_category:
        type: boolean
      name:
        type: string
      user_id:
        type: string
      userID:
        type: string
    required:
    - description
    - name
    - userID
    type: object
  finly-backend_internal_service_category.CreateCategoryResponse:
    properties:
      id:
        type: string
    type: object
  finly-backend_internal_service_category.DeleteCategoryResponse:
    type: object
  finly-backend_internal_service_category.GetCategoryByIDResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_user_category:
        type: boolean
      name:
        type: string
      user_id:
        type: string
    required:
    - description
    - name
    type: object
  finly-backend_internal_service_transaction.CreateTransactionRequest:
    properties:
      amount:
        type: integer
      budget_id:
        type: string
      category_id:
        type: string
      note:
        type: string
      type:
        allOf:
        - $ref: '#/definitions/finly-backend_internal_domain_enums_e_transaction_type.Enum'
        enum:
        - deposit
        - withdraw
      userID:
        type: string
    required:
    - amount
    - budget_id
    - category_id
    - note
    - type
    - userID
    type: object
  finly-backend_internal_service_transaction.CreateTransactionResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      description: Authenticates a user with the provided credentials
      operationId: login-user
      parameters:
      - description: User Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.LoginResponse'
      summary: Login a user
      tags:
      - User
  /auth/logout:
    post:
      description: Logs out a user by invalidating their authentication token
      operationId: logout-user
      parameters:
      - description: Authentication Token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.LogoutResponse'
      summary: Logout a user
      tags:
      - User
  /auth/me:
    post:
      description: Retrieves information about the currently authenticated user
      operationId: get-user-info
      parameters:
      - description: Authentication Token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.MeResponse'
      summary: Get user information
      tags:
      - User
  /auth/refresh:
    post:
      description: Refreshes a user's authentication token by generating a new one
      operationId: refresh-token
      parameters:
      - description: Authentication Token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.RefreshTokenResponse'
      summary: Refresh a user token
      tags:
      - User
  /auth/register:
    post:
      description: Registers a new user with the provided details
      operationId: register-user
      parameters:
      - description: User Details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/finly-backend_internal_service_auth.RegisterResponse'
      summary: RegisterUser a new user
      tags:
      - User
  /budget:
    post:
      description: Creates a new budget for the user with the provided details
      operationId: create-budget
      parameters:
      - description: Budget Details
        in: body
        name: budget
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_budget.CreateBudgetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_budget.CreateBudgetResponse'
      summary: Create a new budget
      tags:
      - Budget
  /budget/{budget_id}:
    get:
      description: Retrieves a budget by its ID for the specified user
      operationId: get-budget-by-id
      parameters:
      - description: Budget ID
        in: path
        name: budget_id
        required: true
        type: string
      - description: User ID
        in: header
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_budget.GetBudgetByIDResponse'
      summary: Get budget by ID
      tags:
      - Budget
  /category:
    get:
      description: Retrieves all categories for the user
      operationId: list-categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/finly-backend_internal_service_category.GetCategoryByIDResponse'
            type: array
      summary: List all categories
      tags:
      - Category
    post:
      description: Creates a new category for the user with the provided details
      operationId: create-category
      parameters:
      - description: Category Details
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_category.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_category.CreateCategoryResponse'
      summary: Create a new category
      tags:
      - Category
  /category/{id}:
    delete:
      description: Deletes the category with the given ID
      operationId: delete-category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_category.DeleteCategoryResponse'
      summary: Delete a category
      tags:
      - Category
    get:
      description: Retrieves the category details for the given ID
      operationId: get-category-by-id
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_category.GetCategoryByIDResponse'
      summary: Get category by ID
      tags:
      - Category
  /transaction:
    post:
      description: Creates a new transaction for the user with the provided details
      operationId: create-transaction
      parameters:
      - description: Transaction Details
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/finly-backend_internal_service_transaction.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/finly-backend_internal_service_transaction.CreateTransactionResponse'
      summary: Create a new transaction
      tags:
      - Transaction
swagger: "2.0"
